#Create Custom Container Image
#Push to DockerHub Registry
---
- hosts: localhost
  tasks: 
  - name: Pull .war artifact from Artifactory
    become: true
    get_url:
      url: http://18.117.87.152/:8082/artifactory/libs-release-local/com/ohwilly/ohwillyApp/1.0-RELEASE/ohwillyApp-1.0-RELEASE.war
      dest: /home/admin
      url_username: admin
      url_password: Lifesucks1

  - name: Rename .war Artifact
    command: mv /home/admin/ohwillyApp-1.0-RELEASE.war /home/admin/ohwilly.war

  - name: Pull Tomcat Container Image
    docker_image:
      name: tomcat:latest
      source: pull

  - name: Build image and with build args
    docker_image:
      name: ohwilly
      build:
        path: /home/admin
        pull: no
        args:
          listen_port: 8080
      source: build

  - name: Log into DockerHub
    docker_login:
      username: pttu01
      password: Youwantion1_

  - name: Push to docker hub
    docker_image:
      name: ohwilly
      repository: pttu01/ohwilly:1.0
      push: yes
      source: local

    
