#K8s Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pttu01-deploy
  labels:
    app: pttu01-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pttu01-app
  template:
    metadata:
      labels:
        app: pttu01-app
    spec:
      containers:
      - name: pttu01-container
        image: pttu01/ohwilly:1.0
        ports:
        - containerPort: 8080
        