#Service Type nodeport
apiVersion: v1
kind: Service
metadata:
  name: pttu01-service
  labels:
    apps: pttu01-app
spec:
  selector:
    app: pttu01-app
  
  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080